# Import necessary libraries
import pandas as pd
from openpyxl import load_workbook
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import matplotlib.pyplot as plt


def generate_report(data, ai_summary: str = ""):
    """
    Generate a PDF report based on the provided data.

    Args:
        data (DataFrame): Processed data containing sales figures by region.
        ai_summary (str): Optional AI-generated executive summary to embed in the PDF.
    """
    # Create a new PDF file
    c = canvas.Canvas("sales_report.pdf", pagesize=letter)
    width, height = letter

    # Set up the title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 50, "Sales Report")

    # Draw a line under the title
    c.line(40, height - 55, width - 40, height - 55)

    # AI Executive Summary section
    y_start = height - 75
    if ai_summary:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(40, y_start, "Executive Summary (AI)")
        y_start -= 15
        c.setFont("Helvetica", 9)
        # Word-wrap the summary into lines of ~100 chars
        words = ai_summary.split()
        line, lines = [], []
        for word in words:
            if len(" ".join(line + [word])) <= 100:
                line.append(word)
            else:
                lines.append(" ".join(line))
                line = [word]
        if line:
            lines.append(" ".join(line))
        for l in lines:
            c.drawString(40, y_start, l)
            y_start -= 12
        y_start -= 8
        c.line(40, y_start, width - 40, y_start)
        y_start -= 15

    # Write the table header
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y_start, "Region")
    c.drawString(250, y_start, "Total Sales ($)")

    # Set up the data rows
    y_position = y_start - 20

    for index, row in data.iterrows():
        c.setFont("Helvetica", 10)
        c.drawString(40, y_position, str(row['Region']))
        c.drawString(250, y_position, f"{row['Total Sales']:.2f}")

        # Move to the next row
        y_position -= 20


    # Add a footer
    c.setFont("Helvetica", 10)
    c.drawString(40, 50, "Generated by Sales Reporting System v1.0")
    c.save()


if __name__ == "__main__":
    # Load the data from the Excel file
    df = pd.read_excel('sales_data.xlsx')

    # Calculate the total sales per region
    regional_totals = df.groupby('Region')['Sales'].sum().reset_index()

    # Save the processed data back to an Excel file
    regional_totals.to_excel('processed_data.xlsx', index=False)

    # Generate the report
    generate_report(regional_totals)