# Import necessary libraries
import pandas as pd
from openpyxl import load_workbook
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import matplotlib.pyplot as plt


def generate_report(data):
    """
    Generate a PDF report based on the provided data.

    Args:
        data (DataFrame): Processed data containing sales figures by region.
    """
    # Create a new PDF file
    c = canvas.Canvas("sales_report.pdf", pagesize=letter)
    width, height = letter

    # Set up the title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 50, "Sales Report")

    # Draw a line under the title
    c.line(40, height - 55, width - 40, height - 55)

    # Write the table header
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, height - 70, "Region")
    c.drawString(180, height - 70, "Total Sales ($)")
    c.drawString(320, height - 70, "Average Sale ($)")

    # Set up the data rows
    y_position = height - 90
    total_sales = data['Total Sales'].sum()
    average_sale = total_sales / len(data) if len(data) > 0 else 0

    for index, row in data.iterrows():
        c.setFont("Helvetica", 10)
        c.drawString(40, y_position, row['Region'])
        c.drawString(180, y_position, f"{row['Total Sales']:.2f}")
        c.drawString(320, y_position, f"{average_sale:.2f}")

        # Move to the next row
        y_position -= 20

    # Add a footer
    c.setFont("Helvetica", 10)
    c.drawString(40, 50, "Generated by Sales Reporting System v1.0")
    c.save()


if __name__ == "__main__":
    # Load the data from the Excel file
    df = pd.read_excel('sales_data.xlsx')

    # Calculate the total sales per region
    regional_totals = df.groupby('Region')['Sales'].sum().reset_index()

    # Save the processed data back to an Excel file
    regional_totals.to_excel('processed_data.xlsx', index=False)

    # Generate the report
    generate_report(regional_totals)